name: Compile OpenSSL 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y build-essential wget

    - name: Download OpenSSL 3
      run: |
        wget https://www.openssl.org/source/openssl-3.2.0.tar.gz
        tar -xvzf openssl-3.2.0.tar.gz

    - name: Compile OpenSSL 3
      run: |
        cd openssl-3.2.0
        ./config
        make -j$(nproc)
        make install

    - name: Upload OpenSSL artifacts
      uses: actions/upload-artifact@v3
      with:
        name: openssl3
        path: /usr/local/ssl
