name: Compile OpenSSL 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up environment
      run: sudo apt-get update && sudo apt-get install -y build-essential wget

    - name: Download OpenSSL 3
      run: |
        wget https://www.openssl.org/source/openssl-3.2.0.tar.gz
        tar -xvzf openssl-3.2.0.tar.gz

    - name: Compile OpenSSL 3
      run: |
        cd openssl-3.2.0
        ./config
        make -j$(nproc)

    - name: List build directory contents
      run: |
        ls -la openssl-3.2.0
        ls -la openssl-3.2.0/bin
        ls -la openssl-3.2.0/lib

        
    - name: Package OpenSSL 3
      run: |
        mkdir -p openssl-package/bin
        mkdir -p openssl-package/lib
        cp -r openssl-3.2.0/bin/* openssl-package/bin/
        cp -r openssl-3.2.0/lib/* openssl-package/lib/

    - name: Upload OpenSSL 3 artifacts
      uses: actions/upload-artifact@v3
      with:
        name: openssl3
        path: openssl-package
